# Generated by Django 5.2.1 on 2026-01-07 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash_type', models.CharField(choices=[('in', 'Cash In'), ('out', 'Cash Out')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('cash_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='accountsApp.client')),
            ],
        ),
    ]
