# Generated by Django 5.2.1 on 2026-01-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0002_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
