# Generated by Django 5.2.1 on 2026-01-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0006_remove_cash_description_remove_expense_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
