# Generated by Django 5.2.1 on 2026-01-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0010_worker_alter_bank_name_alter_expense_bank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
