# Generated by Django 5.2.11 on 2026-02-10 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0011_appsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='accountsApp.company'),
            preserve_default=False,
        ),
    ]
