# Generated by Django 5.2.11 on 2026-02-10 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0012_worker_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='accountsApp.worker')),
            ],
        ),
    ]
