# Generated by Django 5.2.11 on 2026-02-10 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0014_expensesubcategory_expense_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accountsApp.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensesubcategory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accountsApp.company'),
            preserve_default=False,
        ),
    ]
