# Generated by Django 5.2.11 on 2026-02-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0015_expensecategory_company_expensesubcategory_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
