# Generated by Django 5.2.11 on 2026-02-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0016_alter_expensecategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='worker_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accountsApp.workername'),
        ),
    ]
