# Generated by Django 5.2.11 on 2026-02-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0019_alter_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
