# Generated by Django 5.2.11 on 2026-02-12 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0020_alter_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='accountsApp.company'),
            preserve_default=False,
        ),
    ]
