# Generated by Django 5.2.11 on 2026-02-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0023_backuphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicons/'),
        ),
    ]
