# Generated by Django 5.2.11 on 2026-02-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0024_appsettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, help_text='Client location or address', max_length=255, null=True),
        ),
    ]
