# Generated by Django 5.2.11 on 2026-03-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0025_client_location'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('company', 'name', 'location'), name='unique_client_name_location_per_company'),
        ),
    ]
