# Generated by Django 5.2.11 on 2026-03-14 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0026_client_unique_client_name_location_per_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='expensesubcategory',
            unique_together={('company', 'category', 'name')},
        ),
    ]
