# Generated by Django 5.2.11 on 2026-03-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0027_alter_expensecategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='workername',
            unique_together={('worker', 'name')},
        ),
    ]
