# Generated by Django 5.2.11 on 2026-03-19 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0029_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transfer_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='accountsApp.bank')),
                ('to_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='accountsApp.bank')),
            ],
        ),
    ]
