# Generated by Django 5.2.11 on 2026-03-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0030_banktransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
