# Generated by Django 5.2.11 on 2026-03-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0030_banktransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
