# Generated by Django 5.2.11 on 2026-03-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0031_payment_uuid'),
        ('accountsApp', '0032_client_is_active'),
    ]

    operations = [
    ]
