# Generated by Django 5.2.11 on 2026-03-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0033_merge_0031_payment_uuid_0032_client_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='uuid',
        ),
        migrations.AddField(
            model_name='workername',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
