# Generated by Django 5.2.11 on 2026-05-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0034_remove_payment_uuid_workername_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at']},
        ),
    ]
