# Generated by Django 5.2.11 on 2026-05-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0035_alter_activitylog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
